import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import CookieConsent from "@/components/cookiesConsent";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";
import ClientProviders from "./ClientProviders";

const poppins = Poppins({
  variable: "--Poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={`${poppins.variable} antialiased`}>
        <ClientProviders>{children}</ClientProviders>
        <CookieConsent />
      </body>
    </html>
  );
}
